export enum View {
  Dashboard = 'dashboard',
  LeadIntelligence = 'lead-intelligence',
  CompetitorIntel = 'competitor-intel',
  ProjectHub = 'project-hub',
  ResidentialProspecting = 'residential-prospecting',
  InteractiveMap = 'interactive-map',
  SeoDashboard = 'seo-dashboard',
  AiInspection = 'ai-inspection',
  Integrations = 'integrations',
  Settings = 'settings',
  MonthlyReport = 'monthly-report',
  MyIntel = 'my-intel',
  PipedriveAuth = 'pipedrive-auth',
  Reports = 'reports',
  TennisCourtCard = 'tennis-court-card',
  TestView = 'test-view',
  Tooltip = 'tooltip',
}
